package platformer;

import java.applet.Applet;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.Timer;

/**
 * Plays the game Platformer. The objectives and rules of the game are shown on launch.
 * @author Joseph Nielson
 * @verison 1.0 2017-3-7
 *
 */
public class PlatformerGame extends Applet
{
	//Applet
	int aWidth = 1200, aHeight = 600;
	
	//Platforms
	final int PLATFORM_SPACING = 100; 
	final int NUMBER_OF_PLATFORMS = 10;
	final int FIRST_PLATFORM_LOCATION = 550;
	PlatformSet platforms = new PlatformSet(aWidth, FIRST_PLATFORM_LOCATION, NUMBER_OF_PLATFORMS);
	
	//Menu
	int menuX = 100;
	int menuY = 100;
	int menuWidth = aWidth - 200;
	int menuHeight = aHeight - 200;
	Menu openMenu = new Menu(menuX, menuY, menuWidth, menuHeight);
	
	//Timer
	public Timer timer;
	final int FIRING_INTERVAL = 50;
	
	//Conditions
	boolean isPaused = true;
	int downwardVelocity = 2;
	
	/**
	 * Runs when the Applet starts. Sets size and color of Applet and starts timer.
	 */
	public void init()
	{
		//Applet
		setSize(aWidth, aHeight);
		setBackground(Color.white);
		
		//Timer
		timer = new Timer(FIRING_INTERVAL, new PlatformerTimer());
		timer.start();
		
	}//End init
	
	/**
	 * Draws the screen to begin and when repaint() is called.
	 * @param g an object of the Graphics class.
	 */
	public void paint(Graphics g)
	{
		//Draw platforms
		platforms.draw(g);
		
		//Draw menu
		if (isPaused)
		{
			openMenu.draw(g, this);
		}
	}
	
	/**
	 * Runs at given intervals to move objects.
	 * @author Joseph Nielson
	 * @verison 1.0 2017-3-7
	 *
	 */
	public class PlatformerTimer implements ActionListener
	{

		@Override
		public void actionPerformed(ActionEvent e) 
		{
			if (!isPaused)
			{
				platforms.scrollDown(downwardVelocity);
			}
			
			repaint();
			
		}

	}

	
	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 1L;

}
